name: Maven Build and Goals

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Compile with Maven
      run: mvn compile

    - name: Test with Maven
      run: mvn test

    - name: Package with Maven
      run: mvn package

    - name: Install with Maven
      run: mvn install

    - name: Deploy with Maven
      run: mvn deploy

    - name: Clean with Maven
      run: mvn clean

    - name: Generate site with Maven
      run: mvn site

    - name: Deploy site with Maven
      run: mvn site-deploy

    - name: Verify with Maven
      run: mvn verify
